version: "3"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build: .
    command: go main.go
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres-data:
